services:
  local-postgres:
    image: postgres:15
    profiles: [local-db]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: manabandhu
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  local-redis:
    image: redis:7
    profiles: [local-cache]
    ports:
      - '6379:6379'

  meilisearch:
    image: getmeili/meilisearch:v1.5
    environment:
      MEILI_MASTER_KEY: masterKey
    ports:
      - '7700:7700'

  kafka:
    image: bitnami/kafka:3
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'

  zookeeper:
    image: bitnami/zookeeper:3.9
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
    ports:
      - '2181:2181'

  manabandhu-service:
    build: ../../backend/manabandhu-service
    env_file:
      - ../env/neon.env
      - ../env/upstash.env
    environment:
      PORT: 3080
      MEILI_HOST: http://meilisearch:7700
      MEILI_KEY: masterKey
    ports:
      - '3080:3080'
    depends_on:
      - meilisearch

volumes:
  postgres_data:
