server:
  port: ${PORT:3080}

spring:
  application:
    name: manabandhu-backend
  datasource:
    url: jdbc:postgresql://ep-morning-smoke-a4sp6np2-pooler.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_4EDBtGZM3cmQ&sslmode=require&channelBinding=require
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migrations
  redis:
    url: https://smashing-cicada-44566.upstash.io
    token: Aq4WAAIgcDJ9eV-uC8g-UE8adpt6bRicLSZC0H7ox8O6P_AEir2a-A
  jackson:
    serialization:
      write-dates-as-timestamps: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

jwt:
  secret: ${JWT_SECRET:Q2hhbmdlVGhpc1NlY3JldEJ1dGlzVG9vU2hvcnQxMjM0NTY=}

app:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:*}
